// Generated by CoffeeScript 1.7.1
(function() {
  var Sleep,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Sleep = (function(_super) {
    __extends(Sleep, _super);

    function Sleep(code) {
      this.code = code.split(/[\n\s]/).map(this.to_bf).join("");
    }

    Sleep.prototype.to_bf = function(inca) {
      var err;
      try {
        return {
          z: ">",
          zz: "<",
          zzz: "+",
          zzzz: "-",
          zzzzz: ".",
          zzzzzz: ",",
          zzzzzzz: "[",
          zzzzzzzz: "]"
        }[inca.toLowerCase()];
      } catch (_error) {
        err = _error;
        return "";
      }
    };

    return Sleep;

  })(BrainFuck);

  window.Sleep = Sleep;

}).call(this);

//# sourceMappingURL=sleep.map
